tasker/urls.py
from django.conf.urls import url
from django.contrib import admin
from taskerapp import views
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^$', views.home, name='home'),
    url(r'^task/sign-in/$', auth_views.login, {
        'template_name': 'task/sign_in.html',
        },
        name='task-sign-in'),
    url(r'^task/sign-out/$', auth_views.logout, {
        'next_page': '/'},
        name='task-sign-out'),
    url(r'^task/$', views.task_home, name="task-home"),
    url(r'^task/sign-up-learner/$', views.task_sign_up_learner, 
        name='task-sign-up-learner'),
     url(r'^task/sign-up-teacher/$', views.task_sign_up_teacher, 
        name='task-sign-up-teacher'),
    url(r'^task/account/$', views.task_account, 
        name='task-account'),
    url(r'^task/gigs/(?P<id>[0-9]+)/$', views.gig_detail, 
        name='gig-detail'),
    url(r'^task/my-gigs/$', views.my_gigs, 
        name='my-gigs'),
    url(r'^task/create-gig/$', views.create_gig, 
        name='create-gig'),
        url(r'^task/profile/(?P<username>\w+)/$', views.profile, 
        name='profile'),
    url(r'^task/search/$', views.search, 
        name='search'),    
    url(r'^lending-page/$', views.lending_page, 
        name='lending-page'), 
   
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
        
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskerapp/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class Profile(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    status = models.CharField(max_length=500,  blank=True, null=True)
    logo = models.ImageField(upload_to='task_logo/', blank=True, null=True)
    role = models.CharField(max_length=30, blank=True)
    philosopher = models.CharField(max_length=100,  blank=True, null=True)
    
    def __str__(self):
        return self.name

class Gig(models.Model): 
    CATEGORY_CHOICES = (
        ("ЕГЭ егэ английский Английский Язык язык", "История западной философии"),
        ("IELTS ielts шудеы", "Философвские взгляды"),
        ("TOEFL toefl ещуад", "Биография"),
        ("TOEFL toefl ещуад", "Математическая логика"),
        ("TOEFL toefl ещуад", "Иное"),
    )
    
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    answers = RichTextField(blank=True, null=True)
    tasks = RichTextField(blank=True, null=True)
    status = models.BooleanField(default=True)
    user = models.ForeignKey(User)
    songfile = models.FileField(upload_to='songs', blank=True)
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.category

    

class Comment(models.Model):
    user = models.ForeignKey(User)
    content = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.name
# Create your models here.

taskerapp/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from django.contrib.auth.models import User
from taskerapp.models import Profile
from taskerapp.models import Gig
from taskerapp.models import Comment


class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username", "password", "first_name", "last_name", "email")

class UserFormForEdit(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email",)
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()

class ProfileFormForEdit(forms.ModelForm):
    status = forms.CharField(label='About me', widget=forms.Textarea)
    class Meta:
        model = Profile
        fields = ("philosopher", "status","logo",)


class GigForm(forms.ModelForm):
    tasks = forms.CharField(label='Question', widget=forms.Textarea(attrs={'class': 'ckeditor'} ))
    #answers = forms.CharField(label='Answers', widget=forms.Textarea(attrs={'class': 'ckeditor'}))
     #songfile = forms.FileField(label='Speaking', required=False)
    class Meta:
        model = Gig
        fields = ["category", "tasks"]
        # "answers", "songfile", "status"

class CommentForm(forms.Form):
    
    
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'class': 'ckeditor'} ))
   

   

taskerapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from taskerapp.forms import UserForm, ProfileForm, UserFormForEdit, GigForm, CommentForm, ProfileFormForEdit
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Q
from .models import Gig, Profile, Comment
from http.client import responses
from django.http import HttpResponse
from django.urls import reverse
from django.http import JsonResponse
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.z
def home(request):
    return redirect(lending_page)

def lending_page(request):
    return render(request, 'task/lending_page.html', {})

@login_required(login_url='/task/sign-in/' )
def task_home(request):
    gigs = Gig.objects.all().order_by("-create_time")
    paginator = Paginator(gigs, 9) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    
    return render(request, 'task/home.html', {"gigs": queryset})



@login_required(login_url='/task/sign-in/' )
def task_account(request):
    user_form = UserFormForEdit( instance = request.user)
    task_form = ProfileFormForEdit(instance = request.user.profile)
    if request.method == "POST":
        print("eee ,jq")
        user_form = UserFormForEdit(request.POST,  instance = request.user)
        task_form = ProfileFormForEdit(request.POST, request.FILES,  instance = request.user.profile)
        print("eee ,jq")
        if user_form.is_valid() and task_form.is_valid():
            user_form.save()
            task_form.save()
            print("eee ,jq")
            
            return redirect(reverse('profile', kwargs={"username": request.user.username}))
    
    return render(request, 'task/account.html', {
        "user_form": user_form,
        "task_form": task_form
    })

def task_sign_up_learner(request):
    user_form = UserForm()
    task_form = ProfileForm()

    if request.method == "POST":
        user_form = UserForm(request.POST)
        task_form = ProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and task_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_task = task_form.save(commit=False)
            new_task.user = new_user
            new_task.role = "learner"
            new_task.save()
            #new_user.save()

            login(request, authenticate(
                username = user_form.cleaned_data["username"],
                password = user_form.cleaned_data["password"]
            ))

            return redirect(task_home)

    return render(request, 'task/sign_up.html', {
        "user_form": user_form,
        "task_form": task_form
    })

def task_sign_up_teacher(request):
    user_form = UserForm()
    task_form = ProfileForm()

    if request.method == "POST":
        user_form = UserForm(request.POST)
        task_form = ProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and task_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_task = task_form.save(commit=False)
            new_task.user = new_user
            new_task.role = "teacher"
            new_task.save()
            #new_user.save()

            login(request, authenticate(
                username = user_form.cleaned_data["username"],
                password = user_form.cleaned_data["password"]
            ))

            return redirect(task_home)

    return render(request, 'task/sign_up.html', {
        "user_form": user_form,
        "task_form": task_form
    })



  
def gig_detail(request, id):
    
    
   
    gig = Gig.objects.get(id=id)
    profile = Profile.objects.get(user__username=gig.user.username)
    
  
    comment_form = CommentForm()
    content_type = ContentType.objects.get_for_model(Gig)
    obj_id = gig.id
    comments = Comment.objects.filter(content_type=content_type, object_id=obj_id)
    comment_form = CommentForm(request.POST or None)
    
    if comment_form.is_valid(): 
        content_data = comment_form.cleaned_data.get("content")
        new_comment, created = Comment.objects.get_or_create(
            user = request.user,
            content_type = ContentType.objects.get_for_model(Gig),
            object_id = gig.id,
            content = content_data
        )
        context = {
        "gig":gig,
        "comments":comments,
        "comment_form":comment_form
        } 
        return redirect(reverse('gig-detail', kwargs={"id": gig.id}))
    

    context = {
    "gig":gig,
    "comments":comments,
    "comment_form":comment_form,
    "profile":profile
    
    } 
       
        
    response = render(request, 'task/gig_detail.html', context) 
    if not request.COOKIES.get('visits'):        
        response.set_cookie('visits', '1')
    else:
        visits = int(request.COOKIES.get('visits', '1')) + 1
        response.set_cookie('visits', str(visits))
    return response   

    
    

@login_required(login_url='/task/sign-in/' )
def create_gig(request):
    gig_form = GigForm()
    error = ''
    if request.method == "POST":
        gig_form = GigForm(request.POST, request.FILES )
        if gig_form.is_valid():
            gig = gig_form.save(commit=False)
            gig.user = request.user
            gig.save()
            return redirect(my_gigs)
        else:
            error = 'Data is not valid'
    
    show = False
    
    if not request.COOKIES.get('visits_creates'):    
        show = True
    else:
        check = request.COOKIES.get('visits_creates')
        check = int(check)
        if check <= 2:
            show = True

    context = {
    "gig_form":gig_form,
    "error":error,
    "show":show
    
    } 
    


    response = HttpResponse()
    response = render(request, 'task/create_gig.html', context) 
    if not request.COOKIES.get('visits_creates'):        
        response.set_cookie('visits_creates', '1')
        
        return response  
    else:

        
        visits_creates = int(request.COOKIES.get('visits_creates', '1')) + 1
        response.set_cookie('visits_creates', str(visits_creates))
            
        return response  
       
    
     
      


@login_required(login_url='/task/sign-in/' )
def my_gigs(request):
    gigs = Gig.objects.filter(user = request.user)
    return render(request, 'task/my_gigs.html', {"gigs":gigs })

@login_required(login_url='/task/sign-in/' )
def profile(request, username):
    try:
        profile = Profile.objects.get(user__username=username)
    except Profile.DoesNotExist:
        return redirect('/')
    return render(request, 'task/profile.html', {"profile":profile})

@login_required(login_url='/task/sign-in/' )
def search(request): 
  
    gigs = Gig.objects.all().order_by("-create_time")
    
    
    
    query = request.GET.get("q")
    if query == None : 
        query = ""
    
    
    query = query.lower()
    if query:
        gigs = gigs.filter(
            Q(category__icontains=query) |
              Q(tasks__icontains=query)
            )
        paginator = Paginator(gigs, 9) # Show 25 contacts per page
        page = request.GET.get('page')
        isSet = True
        try:
            queryset = paginator.page(page)

        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)
    else:
        queryset = None
        paginator =  None
    
            
    context = {
       "gigs": queryset,
      
    }

    
    return render(request, 'task/search.html', context )

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

taskerapp/templates/task/account.html
{% extends 'base.html' %}
{% load  bootstrap3 %}
{% block page %}

<div class="card">
        <h3 class="text-center card-header">Edit</h3>
    <div class="card-body">
       
        <br>
        
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form user_form %}
            {% bootstrap_form task_form %}
            <br>

            {% buttons %}
            <button type="submit"  class="btn btn-pink float-right ">Update</button>
            <br>
            {% endbuttons %}

        </form>

    </div>

</div>

{% endblock %}

taskerapp/templates/task/create_gig.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block page %}
{{ error }}
<div class="card">
    <h6 class="text-center card-header"> <b>Create question</b></h6>
    <div class="card-body">
        <br>
        {% if  show == True %}
       
        <div style="padding:10px; background: rgba(255, 222, 113, 0.548); border:1px dashed rgba(250, 0, 0, 0.212);">
       
      <div class="text-center"> Рекомендации и правила</div>  <hr> 
      1. Отправлять сообщения и комментарии рекламного характера, а также содержащие внешние ссылки, за исключением ссылок на сайты социальных сетей ("В контакте", "Одноклассники", "онлайн-дневники" и т. п.).

2. Обсуждать действия модераторов и администраторов чата и форума за исключением специального раздела форума. Пользователь может однократно указать модератору или администратору на нарушение правил чата другим пользователем.
3. Заниматься попрошайничеством и выпрашивать дополнительные привилегии у администрации.
4. Заниматься пропагандой расовой и национальной дискриминации, насилия, рекламой наркотиков, порнографии, призывать к свержению законной власти силовым путем, а также любые другие действия и призывы противоречащие действующему законодательству РФ.
5. Отправлять какие-либо сообщения и комменатрии, размещать картинки/фотографии или использовать ники, оскорбляющие общепринятые нормы нравственности.

    </div>
   
      <hr>
      {% endif %}
      {% if  request.COOKIES.visits_creates == "False" %}
     
      {% endif %}
        <br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {% bootstrap_form gig_form %}
            <br>
            {% buttons %}
            <button type="submit" class="btn btn-pink float-right">Create gig</button>
            <br>
            {% endbuttons %}
        </form>
    </div>

</div>
{% endblock %}

taskerapp/templates/task/gig_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block page %}
{% load bootstrap3%}


 <style>
    .Hide {
        display: none;
    }
</style> 

    <div class="col-md-12" style="padding: 0px !important;">
        <div class="card" style="margin-bottom:0px; margin:0px !important; border-radius: 0px; overflow-x: scroll;">
            <div style="padding:20px;">
                <h5 class="text-center"> {{ gig.get_category_display}}
                </h5>
                <hr>


                <!-- <h5 class="text-center "> Question </h5> -->

                {{gig.tasks|safe}}
                  <!-- <img src="/media/{{gig.photo}}" style="display: block;margin: auto;" alt="" class="img-fluid "> 



                 <h5 class="text-center "> Answers </h5>


                {{gig.answers|safe}}

                <h5 class="text-center">
                    Speaking
                </h5>

                <audio style="background: rgb(255, 255, 255); width: 100%;" class="horizontal-alignment" controls>
                    <source src="/media/{{gig.songfile}}" type="audio/mpeg">

                </audio>  
 -->


            </div>



        </div>

        <div class="card wrapperBlock" id="{{gig.user.id}}" onclick="myFunction('{{ gig.user.id }}')" style="margin-top:0px !important;border-top:1px solid white;border-radius: 0px; " data-url="{% url 'profile' gig.user.username %}">
            <div style="padding:20px;">


                <img src="/media/{{gig.user.profile.logo}}" style="clip-path: circle(50.1% at 50% 50%); object-fit: cover;"
                    width="85px" height="85px">
                <div style="display:inline-block; position: absolute; margin-left:10px;">
                    <span style="color:rgba(0, 0, 0, 0.5);"> First name: </span> {{profile.user.first_name}}
                    <br>
                    <span style="color:rgba(0, 0, 0, 0.5);">Last name: </span> {{profile.user.last_name}}
                    <br>
                    
                   
                    <span style="color:rgba(0, 0, 0, 0.5);"> About me: </span> {{profile.status}}
                    <br>
                    

                </div>





            </div>
        </div>




        {% for comment in comments%}

        <div class="comment-wrapper" style=" padding:20px;border:1px solid rgba(0, 123, 255, 0.287);">
                <div style="background: #F4F7F7; padding:10px; border-radius:10px;">
                    {{comment.user.profile.philosopher}} 
                        <span CLASS="float-right"><a href="{% url 'profile' comment.user %}"> {{comment.user.first_name}} {{comment.user.last_name}}</a></span>
                    </div>
              
               <div style="padding:12px;padding-bottom:0px">
            {{comment.content|safe}}
            
        </div>
          
          
       
            <span CLASS="float-right" style="color:rgba(0, 0, 0, 0.5);">{{comment.timestamp}}</span>
        <br>
        </div>

        {% endfor %}

        {% if profile.role == 'teacher' %}
        
       
   
        {% endif %}

        {% if user.profile.role == 'learner' %}
      
       {% endif %}
       {% if user.profile.role == 'teacher' %}
       <div style="padding:1px;  padding-bottom:10px;  background:#F8F8F8;   ">
        <form action="." method="POST" class="text-center">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit" value="Evaluate the answer" class="btn btn-pink ">
        </form>
    </div>
        {% endif %}
     
       
    </div>








{% endblock %}

taskerapp/templates/task/home.html
{% extends 'base.html' %}
{% load bootstrap3% }
{% load staticfiles %}
{% block title %}
Home
{% endblock %}

{% block page %}
<div id="overlay">
    <div class="preloader4" style=" top:35%;"></div>
    
</div>
<div class="content-wrapper ">
    <div class="ViewSelectWrapper" style="width: 100%; height: 32px; background: rgb(255, 255, 255);
     border:1px solid #DADCE0;">
        <i @click="toggleSelectView" class="material-icons" style="float:right; font-size: 30px;color:rgba(0, 0, 0, 0.730); ">
            ${messageView }$</i>
        <!--  <i  @click="toggleSelectView" class="material-icons" style="float:right;  font-size: 27px;  top:2px; position: relative;color:rgba(0, 0, 0, 0.730); ">
                    view_day</i>
                    -->
    </div>
    <div class="row" style="padding: 8px;" :class="{'hideview': isModuleView}">
        {% for gig in gigs %}
        <div class="wrapper-thumbnail col-lg-4">
            <div class="thumbnail  " onclick="myFunction('{{ gig.id }}')" data-url="{% url 'gig-detail' gig.id %}" id="{{gig.id}}">


                <!--<img class="img-thumbnail"  href="{% url 'gig-detail' gig.id %}" src="/media/{{gig.photo}}" > -->
               <br>
                <div class="gig-title text-center">

                    {{ gig.get_category_display}}

                </div>
                <hr>
                <br>
                <br>
                <div class="gig-bottom">

                    <img src="/media/{{gig.user.profile.logo}}" style="clip-path: circle(50.1% at 50% 50%); object-fit: cover;
                top:9px; position: relative; margin-right:6px;"
                        width="40px" height="40px">
                    <span> {{gig.user.username}}<br></span>
                    <small class="gig-time">{{gig.create_time|timesince}} ago</small>

                </div>


            </div>
        </div>

        {% endfor%}


    </div>
    <!----------------------------------------------------------------------------------------------- -->
    <div class="row ListlView" style="padding: 8px;" :class="{'hideview': !isModuleView}">
        {% for gig in gigs %}
        <div class="wrapper-thumbnail col-lg-12">
            <div class="thumbnail  " style=" max-height: 450px ;
        min-height: 200px;" onclick="myFunction('{{ gig.id }}')"
                data-url="{% url 'gig-detail' gig.id %}" id="{{gig.id}}">


                <!--<img class="img-thumbnail"  href="{% url 'gig-detail' gig.id %}" src="/media/{{gig.photo}}" > -->
                <hr>
                <div style="  overflow: hidden;">
                    <div class="text-center" style="max-height: 300px; overflow-y: scroll;  position: relative;  right: -20px;
            margin-left: -20px;
            ">

                        {{ gig.get_category_display}}
                        {{gig.tasks|safe|truncatechars_html:1700}}
                    </div>
                </div>
                <hr>
                <br>
                <br>
                <div class="gig-bottom">

                    <img src="/media/{{gig.user.profile.logo}}" style="clip-path: circle(50.1% at 50% 50%); object-fit: cover;
                top:9px; position: relative; margin-right:6px;"
                        width="40px" height="40px">
                    <span> {{gig.user.username}}<br></span>
                    <small class="gig-time">{{gig.create_time|timesince}} ago</small>

                </div>


            </div>
        </div>

        {% endfor%}


    </div>


    <br>
    <div style="width: 100%">
        <div class="pagination " style="  transform: translate(-50%);
    position: absolute;
    left: 50%;">
            <span class="step-links">
                {% if gigs.has_previous %}
                <a href="?page={{ gigs.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ gigs.number }} of {{ gigs.paginator.num_pages }}.
                </span>

                {% if gigs.has_next %}
                <a href="?page={{ gigs.next_page_number }}">next</a>
                {% endif %}
            </span>

        </div>
        <br>
    </div>
</div>









<!-- <div class="card">
        <div class="card-body">
            <h3 class="text-center"> <b>{% block heading %}gigi{% endblock %}</b></h3>
          
      
        </div>
    </div> -->

<!-- <p> ${ message }$ </p> -->


{% endblock %}

taskerapp/templates/task/my_gigs.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page %}

<div class="card">
    <h4 class="text-center card-header"> My questions</h4>
    <div class="card-body">
        <table class="table table-bordered table-striped">
            <thead class="">
                <tr>
                  <th>
                        <th> title</th>
                        <th>create time</th>
                        
                    </th>

                </tr>
            </thead>
            <tbody>
                {% for gig in gigs %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'gig-detail' gig.id %}">  {{ gig.get_category_display}}
                        </a></td>
                    <td>{{gig.create_time}}</td>
                    

                </tr>
                {% endfor %}
            </tbody>

        </table>


    </div>

</div>

{% endblock %}

taskerapp/templates/task/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page %}




<form class="" action="" method='GET'>
    <div class="card-body row " style="padding-left: 16px; padding-right: 16px; padding-top:10px; padding-bottom:15px;">

        <!--end of col-->
        <div class="col" style="padding:0px !important;  padding-right:0px;">
            <input class="form-control form-control-lg border-radius-none " type="text" name='q' placeholder="search here"
                value='{{ request.GET.get.q }}'>
        </div>
        <!--end of col-->
        <div class="col-auto" style="padding:0px;">

            <input class="btn btn-lg btn-primary search-btn" type="submit" value="Search" />
        </div>
        <!--end of col-->
        {{isSet}}
    </div>
</form>

{% if gigs %}<div class="ViewSelectWrapper" style="width: 100%; height: 32px; background: rgb(255, 255, 255);
        border:1px solid #DADCE0;">
    <i @click="toggleSelectView" class="material-icons" style="float:right; font-size: 30px;color:rgba(0, 0, 0, 0.730); ">
        ${messageView }$</i>
    <!--  <i  @click="toggleSelectView" class="material-icons" style="float:right;  font-size: 27px;  top:2px; position: relative;color:rgba(0, 0, 0, 0.730); ">
                       view_day</i>
                       -->
</div> {% else %}
&#160 {% endif %}



<div class="row" style="padding: 8px;" :class="{'hideview': isModuleView}">

    {% for gig in gigs %}
    <div class="wrapper-thumbnail col-lg-4">
        <div class="thumbnail  " onclick="myFunction('{{ gig.id }}')" data-url="{% url 'gig-detail' gig.id %}" id="{{gig.id}}">


            <!--<img class="img-thumbnail"  href="{% url 'gig-detail' gig.id %}" src="/media/{{gig.photo}}" > -->
            <br>
            <div class="gig-title text-center">

                {{ gig.get_category_display}}

            </div>
            <hr>
            <br>
            <br>
            <div class="gig-bottom">

                <img src="/media/{{gig.user.profile.logo}}" style="clip-path: circle(50.1% at 50% 50%); object-fit: cover;
                        top:9px; position: relative; margin-right:6px;"
                    width="40px" height="40px">
                <span> {{gig.user.username}}<br></span>
                <small class="gig-time">{{gig.create_time|timesince}} ago</small>

            </div>


        </div>
    </div>

    {% endfor%}


</div>

<div class="row ListlView" style="padding: 8px;" :class="{'hideview': !isModuleView}">
    {% for gig in gigs %}
    <div class="wrapper-thumbnail col-lg-12">
        <div class="thumbnail  " style=" max-height: 450px ;
                min-height: 200px;" onclick="myFunction('{{ gig.id }}')"
            data-url="{% url 'gig-detail' gig.id %}" id="{{gig.id}}">


            <!--<img class="img-thumbnail"  href="{% url 'gig-detail' gig.id %}" src="/media/{{gig.photo}}" > -->
            <hr>
            <div style="  overflow: hidden;">
                <div class="text-center" style="max-height: 300px; overflow-y: scroll; position: relative;  right: -20px;
                    margin-left: -20px;
                    ">

                    {{ gig.get_category_display}}
                    {{gig.tasks|safe|truncatechars_html:1700}}
                </div>
            </div>
            <hr>
            <br>
            <br>
            <div class="gig-bottom">

                <img src="/media/{{gig.user.profile.logo}}" style="clip-path: circle(50.1% at 50% 50%); object-fit: cover;
                        top:9px; position: relative; margin-right:6px;"
                    width="40px" height="40px">
                <span> {{gig.user.username}}<br></span>
                <small class="gig-time">{{gig.create_time|timesince}} ago</small>

            </div>


        </div>
    </div>

    {% endfor%}


</div>



<br>
<div style="width: 100%">
    <div class="pagination " style="  transform: translate(-50%);
        position: absolute;
        left: 50%;">
        <span class="step-links">
            {% if gigs.has_previous %}
            <a href="?page={{ gigs.previous_page_number }}&q={{request.GET.q}}">previous</a>
            {% endif %}

            <span class="current">

                {% if gigs %} Page {% else %} &#160; {{ gigs.number}} {% endif %}
                {{ gigs.number }}
                {% if gigs %} of {% else %} &#160; {{ gigs.number}} {% endif %}
                {{ gigs.paginator.num_pages }}
            </span>

            {% if gigs.has_next %}
            <a href="?page={{ gigs.next_page_number }}&q={{request.GET.q}}">next</a>
            {% endif %}
        </span>

    </div>
    <br>
</div>

{% endblock %}